server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5431
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
